### ISSUE TITLE
Wiki cooperation?

### ISSUE THREAD

**Issue by Tomorrowdawn** [gjfLeo/summoners-summit#1]
能否开放一个公共端口让其他人也可以参与数据录入？

或者可以使用授权码形式，让授信的个人或者组织录入赛事数据。

**Comment by gjfLeo** [comment]
现在项目用的是静态页面生成，也就是所有数据都是直接写在代码里的，所以开放端口可能不太好办。
至于授权码形式指的是什么？

其实我在考虑是不是应该把数据部分的格式再精简一下，这样有意向的人可以直接在GitHub上在线编辑提PR，或者我可以直接开代码编辑权限之类的

**Comment by Tomorrowdawn** [comment]
> 现在项目用的是静态页面生成，也就是所有数据都是直接写在代码里的，所以开放端口可能不太好办。 至于授权码形式指的是什么？
> 
> 其实我在考虑是不是应该把数据部分的格式再精简一下，这样有意向的人可以直接在GitHub上在线编辑提PR，或者我可以直接开代码编辑权限之类的

就是api加一个特定的授权码。一般的api都是所有人可访问的，如果你怕有人乱填数据就可以加一个密码，只有特定的密码可以访问api。

你的数据难道是硬编码的吗？如果不是的话，可以写一个api界面，让其他人post上来就好了。

我对JS不熟悉，如果是有什么代码上的难点的话不太能帮上忙，不好意思。我用django做过网站后台，它生成api页面非常简单，想来不难。

**Comment by gjfLeo** [comment]
目前确实是硬编码的，纯前端项目，没有数据库，也没有API。大致就是数据直接写在代码里，然后网站编译的时候读数据生成好所有的静态HTML页面。用户访问的时候只涉及页面跳转，对应页面上的数据已经预渲染完了，不需要请求数据这一步。

所以我也在思考该怎么放开别人的协助_ (:з」∠)_
