### ISSUE TITLE
Lyney/Fischl/Nahida deck share code is invalid

### ISSUE THREAD

**Issue by RoxieRabbitGameDev** [gjfLeo/summoners-summit#103]
EZGQOBoNA+AQ9ZcPCVBx9jAPE2EBCDMQE4FBOzQTE7FgCsYQDLFgC9EQDdFQEdURDTAA This share code for Lyney/Fischl/Nahida deck is invalid

**Comment by gjfLeo** [comment]
![image](https://github.com/gjfLeo/summoners-summit/assets/27762219/7cc1a279-a1fa-40e4-9efb-954edf16851c)
I can't reproduce that _(:з」∠)_
