### ISSUE TITLE
Data Correction

### ISSUE THREAD

**Issue by TB1aze** [gjfLeo/summoners-summit#105]
[斗鱼七圣召唤资格赛](https://gjfleo.github.io/summoners-summit/tournament/40c26b52c28d0d1a)
16进4
A组
第2场 - 轮舞曲 VS 遗尘音序

轮舞曲 won game 2: [Replay](https://v.douyu.com/show/Kg1VWR8nD1o7GbNA)

**Comment by gjfLeo** [comment]
Thanks!
