### ISSUE TITLE
希望加一个“按角色查找阵容”和“按阵容查找对局”的功能

### ISSUE THREAD

**Issue by oxygen-dioxide** [gjfLeo/summoners-summit#2]
比如说我记得有一局是无相之雷OTK，但是不记得具体是哪个比赛哪一局了。可以在阵容界面按角色筛选，进入单个阵容的界面后可以在“对阵数据”部分展开对每个对手阵容的对局列表，并提供跳转至对局录像的链接

**Comment by gjfLeo** [comment]
收到，会考虑阵容界面筛选和对局列表功能~

**Comment by gjfLeo** [comment]
这两个功能已经加上了😃
