### ISSUE TITLE
tcg share code edge case

### ISSUE THREAD

**Issue by theBowja** [gjfLeo/summoners-summit#88]
`AzHBejwIErHxfkgLBQFxpk8MBtGhxVsNBrHB0l4PBoHRAGMQB/JBCWsRE4JSESYSCAEB`

missing 1 card

**Comment by theBowja** [comment]
https://github.com/gjfLeo/summoners-summit/blob/63b96b07cf6f8f907696d0a1cedfee2f285cefe6/utils/decks/share-code.ts#L52

if ` byteArray[2 * i] = 0` and `lastByte = 1`, then `byteArray[2 * i] - lastByte = -1` but it needs to overflow and turn into `255` instead.

**Comment by gjfLeo** [comment]
Thank you for reporting!

**Comment by gjfLeo** [comment]
BTW, the encoding part is also fixed. 😄
